["Radius Settings"]
	#Excavation radius for Wooden Excavator (radius 1 = 3×1 area)
	#Range: > 0
	Gold = 1
	#Excavation radius for Wooden Excavator (radius 1 = 3×1 area)
	#Range: > 0
	Redstone = 1
	#Excavation radius for Wooden Excavator (radius 1 = 3×1 area)
	#Range: > 0
	Netherite = 1
	#Excavation radius for Wooden Excavator (radius 1 = 3×1 area)
	#Range: > 0
	Wooden = 1
	#Excavation radius for Wooden Excavator (radius 1 = 3×1 area)
	#Range: > 0
	Emerald = 1
	#Excavation radius for Wooden Excavator (radius 1 = 3×1 area)
	#Range: > 0
	Obsidian = 1
	#Excavation radius for Wooden Excavator (radius 1 = 3×1 area)
	#Range: > 0
	Lapis = 1
	#Excavation radius for Wooden Excavator (radius 1 = 3×1 area)
	#Range: > 0
	Iron = 1
	#Excavation radius for Wooden Excavator (radius 1 = 3×1 area)
	#Range: > 0
	Diamond = 1
	#Excavation radius for Wooden Excavator (radius 1 = 3×1 area)
	#Range: > 0
	Stone = 1

["Durability Settings"]
	#Durability of the gold excavator.
	#Range: > 0
	Gold = 750
	#Durability of the redstone excavator.
	#Range: > 0
	Redstone = 1100
	#Durability of the netherite excavator.
	#Range: > 0
	Netherite = 13675
	#Durability of the wooden excavator.
	#Range: > 0
	Wooden = 302
	#Durability of the emerald excavator.
	#Range: > 0
	Emerald = 9768
	#Durability of the obsidian excavator.
	#Range: > 0
	Obsidian = 11200
	#Durability of the lapis excavator.
	#Range: > 0
	Lapis = 1100
	#Durability of the iron excavator.
	#Range: > 0
	Iron = 1300
	#Durability of the diamond excavator.
	#Range: > 0
	Diamond = 8025
	#Durability of the stone excavator.
	#Range: > 0
	Stone = 650
